pip install flask-cors"""Seed vehicles for Tri State Auto Brokers"""

CAR_IMAGES = {
    'mercedes1': 'https://images.unsplash.com/photo-1582828715181-338a8e04ba53?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200',
    'mercedes2': 'https://images.unsplash.com/photo-1599912027765-a69c78bfa3aa?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200',
    'mercedes3': 'https://images.unsplash.com/photo-1610099610040-ab19f3a5ec35?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200',
    'mercedes4': 'https://images.unsplash.com/photo-1546518071-fddcdda7580a?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200',
    'rover1': 'https://images.unsplash.com/photo-1638686302275-0e87df720aca?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200',
    'rover2': 'https://images.unsplash.com/photo-1637859460045-ac3ae9ced99d?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200',
    'rover3': 'https://images.unsplash.com/photo-1725815761064-b84c3f4f9b94?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200',
    'rover4': 'https://images.unsplash.com/photo-1549632891-a0bea6d0355b?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200',
}

COMMON_FEATURES = [
    'Child Safety Door Locks', 'Traction Control', 'Passenger Airbag',
    'Leather Steering Wheel', 'Tire Pressure Monitor', 'Subwoofer',
    'Power Windows', 'Vehicle Anti-Theft', 'Driver Airbag', 'Keyless Entry',
    'Tachometer', 'Telescopic Steering Column', 'AM/FM Radio',
    'Driver Multi-Adjustable Power Seat', 'Daytime Running Lights',
    'Rain Sensing Wipers', 'Power Door Locks', 'Vehicle Stability Control System',
    'Side Head Curtain Airbag', 'Cruise Control', 'Steering Wheel Mounted Controls',
    'Trip Computer', 'Telematics System', 'Power Sunroof',
    'Electrochromic Interior Rearview Mirror', 'ABS Brakes', 'Front Side Airbag',
    'Air Conditioning', 'Tilt Steering', 'Adjustable Foot Pedals', 'Navigation Aid',
    'Front Power Lumbar Support', 'Alloy Wheels', 'Rear Window Defogger',
]


def _img(*keys):
    return [{"url": CAR_IMAGES[k], "public_id": None} for k in keys]


SEED_VEHICLES = [
    {
        'stock_number': '204766', 'year': 2018, 'make': 'Land Rover',
        'model': 'Range Rover Velar', 'trim': 'P250 R-Dynamic HSE Diesel',
        'price': 'Call for price!', 'down_payment': '$1,000 Down',
        'mileage': 45320, 'engine': '2.0L L4 DIESEL DOHC 16V TURBO',
        'transmission': 'SPEED AUTOMATIC', 'drivetrain': 'AWD',
        'vin': 'SALYL2RV6JA123456', 'exterior_color': 'BLACK',
        'interior_color': 'BLACK', 'fuel_type': 'Diesel',
        'features': COMMON_FEATURES,
        'images': _img('rover1', 'rover2', 'rover3', 'rover4'),
    },
    {
        'stock_number': '204740', 'year': 2017, 'make': 'Mercedes-Benz',
        'model': 'C-Class', 'trim': 'AMG C43 Sedan',
        'price': 'Call for price!', 'down_payment': '$1000 Down',
        'mileage': 38210, 'engine': '3.0L V6 DOHC 24V TURBO',
        'transmission': 'SPEED AUTOMATIC', 'drivetrain': 'AWD',
        'vin': 'WDDWJ6EB1HF123001', 'exterior_color': 'WHITE',
        'interior_color': 'BLACK', 'fuel_type': 'Gasoline',
        'features': COMMON_FEATURES,
        'images': _img('mercedes1', 'mercedes2', 'mercedes3'),
    },
    {
        'stock_number': '204748', 'year': 2017, 'make': 'Mercedes-Benz',
        'model': 'C-Class', 'trim': 'C300 Coupe',
        'price': 'Call for price!', 'down_payment': '$1000 Down',
        'mileage': 34396, 'engine': '2.0L L4 DOHC 16V TURBO',
        'transmission': 'SPEED AUTOMATIC', 'drivetrain': 'RWD',
        'vin': 'WDDWJ4JB3HF505656', 'exterior_color': 'DIAMOND WHITE',
        'interior_color': 'SADDLE BROWN/BLACK', 'fuel_type': 'Gasoline',
        'features': COMMON_FEATURES,
        'images': _img('mercedes2', 'mercedes1', 'mercedes3', 'mercedes4'),
    },
    {
        'stock_number': '204751', 'year': 2017, 'make': 'Mercedes-Benz',
        'model': 'C-Class', 'trim': 'C300 Sedan',
        'price': 'Call for price!', 'down_payment': '$1000 Down',
        'mileage': 41250, 'engine': '2.0L L4 DOHC 16V TURBO',
        'transmission': 'SPEED AUTOMATIC', 'drivetrain': 'RWD',
        'vin': 'WDDWF4JB1HR123456', 'exterior_color': 'SILVER',
        'interior_color': 'BLACK', 'fuel_type': 'Gasoline',
        'features': COMMON_FEATURES,
        'images': _img('mercedes3', 'mercedes1'),
    },
    {
        'stock_number': '204754', 'year': 2018, 'make': 'Mercedes-Benz',
        'model': 'C-Class', 'trim': 'C300 Sedan',
        'price': 'Call for price!', 'down_payment': '$1,000',
        'mileage': 29800, 'engine': '2.0L L4 DOHC 16V TURBO',
        'transmission': 'SPEED AUTOMATIC', 'drivetrain': 'RWD',
        'vin': 'WDDWF4JB2JR654321', 'exterior_color': 'OBSIDIAN BLACK',
        'interior_color': 'BEIGE', 'fuel_type': 'Gasoline',
        'features': COMMON_FEATURES,
        'images': _img('mercedes4', 'mercedes2'),
    },
    {
        'stock_number': '204760', 'year': 2018, 'make': 'Mercedes-Benz',
        'model': 'E-Class', 'trim': 'E300 Luxury Sedan',
        'price': 'Call for price!', 'down_payment': '$1000 Down',
        'mileage': 32105, 'engine': '2.0L L4 DOHC 16V TURBO',
        'transmission': 'SPEED AUTOMATIC', 'drivetrain': 'RWD',
        'vin': 'WDDZF4JB1JA987654', 'exterior_color': 'IRIDIUM SILVER',
        'interior_color': 'MACCHIATO BEIGE', 'fuel_type': 'Gasoline',
        'features': COMMON_FEATURES,
        'images': _img('mercedes1', 'mercedes3'),
    },
    {
        'stock_number': '204762', 'year': 2018, 'make': 'Mercedes-Benz',
        'model': 'E-Class', 'trim': 'E300 Luxury Sedan',
        'price': 'Call for price!', 'down_payment': '$1000 Down',
        'mileage': 37890, 'engine': '2.0L L4 DOHC 16V TURBO',
        'transmission': 'SPEED AUTOMATIC', 'drivetrain': 'AWD',
        'vin': 'WDDZF4KB5JA111222', 'exterior_color': 'SELENITE GREY',
        'interior_color': 'BLACK', 'fuel_type': 'Gasoline',
        'features': COMMON_FEATURES,
        'images': _img('mercedes2', 'mercedes4'),
    },
    {
        'stock_number': '204770', 'year': 2020, 'make': 'Mercedes-Benz',
        'model': 'GLA-Class', 'trim': 'GLA250 4MATIC',
        'price': 'Call for price!', 'down_payment': '$1000 Down',
        'mileage': 24560, 'engine': '2.0L L4 DOHC 16V TURBO',
        'transmission': 'SPEED AUTOMATIC', 'drivetrain': 'AWD',
        'vin': 'WDCTG4EB6LJ556677', 'exterior_color': 'POLAR WHITE',
        'interior_color': 'BLACK', 'fuel_type': 'Gasoline',
        'features': COMMON_FEATURES,
        'images': _img('rover2', 'rover1'),
    },
    {
        'stock_number': '204772', 'year': 2017, 'make': 'Mercedes-Benz',
        'model': 'GLA-Class', 'trim': 'GLA250',
        'price': 'Call for price!', 'down_payment': '$1000 Down',
        'mileage': 51230, 'engine': '2.0L L4 DOHC 16V TURBO',
        'transmission': 'SPEED AUTOMATIC', 'drivetrain': 'FWD',
        'vin': 'WDCTG4EB6HJ998877', 'exterior_color': 'NIGHT BLACK',
        'interior_color': 'BLACK', 'fuel_type': 'Gasoline',
        'features': COMMON_FEATURES,
        'images': _img('rover3', 'rover4'),
    },
    {
        'stock_number': '204774', 'year': 2018, 'make': 'Mercedes-Benz',
        'model': 'GLA-Class', 'trim': 'GLA250',
        'price': 'Call for price!', 'down_payment': '$1000 Down',
        'mileage': 44100, 'engine': '2.0L L4 DOHC 16V TURBO',
        'transmission': 'SPEED AUTOMATIC', 'drivetrain': 'FWD',
        'vin': 'WDCTG4EB2JJ334455', 'exterior_color': 'COSMOS BLACK',
        'interior_color': 'ASH', 'fuel_type': 'Gasoline',
        'features': COMMON_FEATURES,
        'images': _img('rover4', 'rover2'),
    },
    {
        'stock_number': '204776', 'year': 2020, 'make': 'Mercedes-Benz',
        'model': 'GLC-Class', 'trim': 'GLC300 4MATIC',
        'price': 'Call for price!', 'down_payment': '$1000 Down',
        'mileage': 27890, 'engine': '2.0L L4 DOHC 16V TURBO',
        'transmission': 'SPEED AUTOMATIC', 'drivetrain': 'AWD',
        'vin': 'W1NKM4KB0LF778899', 'exterior_color': 'MOJAVE SILVER',
        'interior_color': 'BLACK', 'fuel_type': 'Gasoline',
        'features': COMMON_FEATURES,
        'images': _img('rover1', 'rover3'),
    },
    {
        'stock_number': '204778', 'year': 2017, 'make': 'Mercedes-Benz',
        'model': 'GLE-Class', 'trim': 'AMG GLE 43',
        'price': 'Call for price!', 'down_payment': '$1000 Down',
        'mileage': 48750, 'engine': '3.0L V6 DOHC 24V TURBO',
        'transmission': 'SPEED AUTOMATIC', 'drivetrain': 'AWD',
        'vin': '4JGDA6EB6HA112233', 'exterior_color': 'DIAMOND WHITE',
        'interior_color': 'BLACK/RED', 'fuel_type': 'Gasoline',
        'features': COMMON_FEATURES,
        'images': _img('rover2', 'rover4'),
    },
    {
        'stock_number': '204780', 'year': 2018, 'make': 'Mercedes-Benz',
        'model': 'GLC-Class', 'trim': 'GLC300 4MATIC',
        'price': 'Call for price!', 'down_payment': '$1000 Down',
        'mileage': 35670, 'engine': '2.0L L4 DOHC 16V TURBO',
        'transmission': 'SPEED AUTOMATIC', 'drivetrain': 'AWD',
        'vin': 'WDC0G4KB0JF445566', 'exterior_color': 'LUNAR BLUE',
        'interior_color': 'BLACK', 'fuel_type': 'Gasoline',
        'features': COMMON_FEATURES,
        'images': _img('mercedes3', 'mercedes1'),
    },
    {
        'stock_number': '204782', 'year': 2017, 'make': 'Mercedes-Benz',
        'model': 'S-Class', 'trim': 'S550',
        'price': 'Call for price!', 'down_payment': '$1000 Down',
        'mileage': 32564, 'engine': '4.7L V8 DOHC 32V TURBO',
        'transmission': 'SPEED AUTOMATIC', 'drivetrain': 'RWD',
        'vin': 'WDDUG8CB6HA557788', 'exterior_color': 'ANTHRACITE BLUE',
        'interior_color': 'PORCELAIN', 'fuel_type': 'Gasoline',
        'features': COMMON_FEATURES,
        'images': _img('mercedes4', 'mercedes2'),
    },
    {
        'stock_number': '204784', 'year': 2017, 'make': 'Mercedes-Benz',
        'model': 'SL-Class', 'trim': 'SL550',
        'price': 'Call for price!', 'down_payment': '$1000 Down',
        'mileage': 22350, 'engine': '4.7L V8 DOHC 32V TURBO',
        'transmission': 'SPEED AUTOMATIC', 'drivetrain': 'RWD',
        'vin': 'WDDJK7DA5HF119966', 'exterior_color': 'DESIGNO CARDINAL RED',
        'interior_color': 'BLACK', 'fuel_type': 'Gasoline',
        'features': COMMON_FEATURES,
        'images': _img('mercedes1', 'mercedes4'),
    },
]
