// Mock data for Tri State Auto Brokers clone

export const CAR_IMAGES = {
  mercedesSedan1: 'https://images.unsplash.com/photo-1582828715181-338a8e04ba53?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200',
  mercedesSedan2: 'https://images.unsplash.com/photo-1599912027765-a69c78bfa3aa?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200',
  mercedesSedan3: 'https://images.unsplash.com/photo-1610099610040-ab19f3a5ec35?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200',
  mercedesSedan4: 'https://images.unsplash.com/photo-1546518071-fddcdda7580a?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200',
  rangeRover1: 'https://images.unsplash.com/photo-1638686302275-0e87df720aca?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200',
  rangeRover2: 'https://images.unsplash.com/photo-1637859460045-ac3ae9ced99d?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200',
  rangeRover3: 'https://images.unsplash.com/photo-1725815761064-b84c3f4f9b94?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200',
  rangeRover4: 'https://images.unsplash.com/photo-1549632891-a0bea6d0355b?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200',
};

export const HERO_SLIDES = [
  {
    id: 1,
    image: 'https://images.unsplash.com/photo-1585390062628-be8608aa7d83?crop=entropy&cs=srgb&fm=jpg&q=85&w=1920',
    title: 'Save Thousands Over Retail',
    subtitle: 'Let us buy at auction for you',
  },
  {
    id: 2,
    image: 'https://images.pexels.com/photos/164634/pexels-photo-164634.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=900&w=1920',
    title: 'Wholesale Prices, Dealer Only',
    subtitle: 'Flat $600 service fee - no hidden costs',
  },
  {
    id: 3,
    image: 'https://images.unsplash.com/photo-1643792801605-1f8081811439?crop=entropy&cs=srgb&fm=jpg&q=85&w=1920',
    title: 'Find Your Exact Vehicle',
    subtitle: 'We locate the make, model, color you want',
  },
  {
    id: 4,
    image: 'https://images.unsplash.com/photo-1653565217811-85b41bcd1edb?crop=entropy&cs=srgb&fm=jpg&q=85&w=1920',
    title: 'Trusted Since 2010',
    subtitle: 'Hundreds of happy customers',
  },
];

export const HAPPY_CUSTOMER_IMG =
  'https://images.unsplash.com/photo-1643792801605-1f8081811439?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200';

const commonFeatures = [
  'Child Safety Door Locks',
  'Traction Control',
  'Passenger Airbag',
  'Leather Steering Wheel',
  'Tire Pressure Monitor',
  'Subwoofer',
  'Power Windows',
  'Vehicle Anti-Theft',
  'Driver Airbag',
  'Keyless Entry',
  'Tachometer',
  'Telescopic Steering Column',
  'AM/FM Radio',
  'Driver Multi-Adjustable Power Seat',
  'Daytime Running Lights',
  'Rain Sensing Wipers',
  'Power Door Locks',
  'Vehicle Stability Control System',
  'Side Head Curtain Airbag',
  'Cruise Control',
  'Steering Wheel Mounted Controls',
  'Trip Computer',
  'Telematics System',
  'Power Sunroof',
  'Electrochromic Interior Rearview Mirror',
  'ABS Brakes',
  'Front Side Airbag',
  'Air Conditioning',
  'Tilt Steering',
  'Adjustable Foot Pedals',
  'Navigation Aid',
  'Front Power Lumbar Support',
  'Alloy Wheels',
  'Rear Window Defogger',
];

export const VEHICLES = [
  {
    id: '204766',
    year: 2018,
    make: 'Land Rover',
    model: 'Range Rover Velar',
    trim: 'P250 R-Dynamic HSE Diesel',
    price: 'Call for price!',
    downPayment: '$1,000 Down',
    mileage: 45320,
    engine: '2.0L L4 DIESEL DOHC 16V TURBO',
    transmission: 'SPEED AUTOMATIC',
    drivetrain: 'AWD',
    vin: 'SALYL2RV6JA123456',
    exteriorColor: 'BLACK',
    interiorColor: 'BLACK',
    fuelType: 'Diesel',
    stockNumber: '204766',
    images: [CAR_IMAGES.rangeRover1, CAR_IMAGES.rangeRover2, CAR_IMAGES.rangeRover3, CAR_IMAGES.rangeRover4],
    features: commonFeatures,
  },
  {
    id: '204740',
    year: 2017,
    make: 'Mercedes-Benz',
    model: 'C-Class',
    trim: 'AMG C43 Sedan',
    price: 'Call for price!',
    downPayment: '$1000 Down',
    mileage: 38210,
    engine: '3.0L V6 DOHC 24V TURBO',
    transmission: 'SPEED AUTOMATIC',
    drivetrain: 'AWD',
    vin: 'WDDWJ6EB1HF123001',
    exteriorColor: 'WHITE',
    interiorColor: 'BLACK',
    fuelType: 'Gasoline',
    stockNumber: '204740',
    images: [CAR_IMAGES.mercedesSedan1, CAR_IMAGES.mercedesSedan2, CAR_IMAGES.mercedesSedan3],
    features: commonFeatures,
  },
  {
    id: '204748',
    year: 2017,
    make: 'Mercedes-Benz',
    model: 'C-Class',
    trim: 'C300 Coupe',
    price: 'Call for price!',
    downPayment: '$1000 Down',
    mileage: 34396,
    engine: '2.0L L4 DOHC 16V TURBO',
    transmission: 'SPEED AUTOMATIC',
    drivetrain: 'RWD',
    vin: 'WDDWJ4JB3HF505656',
    exteriorColor: 'DIAMOND WHITE',
    interiorColor: 'SADDLE BROWN/BLACK',
    fuelType: 'Gasoline',
    stockNumber: '204748',
    images: [CAR_IMAGES.mercedesSedan2, CAR_IMAGES.mercedesSedan1, CAR_IMAGES.mercedesSedan3, CAR_IMAGES.mercedesSedan4],
    features: commonFeatures,
  },
  {
    id: '204751',
    year: 2017,
    make: 'Mercedes-Benz',
    model: 'C-Class',
    trim: 'C300 Sedan',
    price: 'Call for price!',
    downPayment: '$1000 Down',
    mileage: 41250,
    engine: '2.0L L4 DOHC 16V TURBO',
    transmission: 'SPEED AUTOMATIC',
    drivetrain: 'RWD',
    vin: 'WDDWF4JB1HR123456',
    exteriorColor: 'SILVER',
    interiorColor: 'BLACK',
    fuelType: 'Gasoline',
    stockNumber: '204751',
    images: [CAR_IMAGES.mercedesSedan3, CAR_IMAGES.mercedesSedan1],
    features: commonFeatures,
  },
  {
    id: '204754',
    year: 2018,
    make: 'Mercedes-Benz',
    model: 'C-Class',
    trim: 'C300 Sedan',
    price: 'Call for price!',
    downPayment: '$1,000',
    mileage: 29800,
    engine: '2.0L L4 DOHC 16V TURBO',
    transmission: 'SPEED AUTOMATIC',
    drivetrain: 'RWD',
    vin: 'WDDWF4JB2JR654321',
    exteriorColor: 'OBSIDIAN BLACK',
    interiorColor: 'BEIGE',
    fuelType: 'Gasoline',
    stockNumber: '204754',
    images: [CAR_IMAGES.mercedesSedan4, CAR_IMAGES.mercedesSedan2],
    features: commonFeatures,
  },
  {
    id: '204760',
    year: 2018,
    make: 'Mercedes-Benz',
    model: 'E-Class',
    trim: 'E300 Luxury Sedan',
    price: 'Call for price!',
    downPayment: '$1000 Down',
    mileage: 32105,
    engine: '2.0L L4 DOHC 16V TURBO',
    transmission: 'SPEED AUTOMATIC',
    drivetrain: 'RWD',
    vin: 'WDDZF4JB1JA987654',
    exteriorColor: 'IRIDIUM SILVER',
    interiorColor: 'MACCHIATO BEIGE',
    fuelType: 'Gasoline',
    stockNumber: '204760',
    images: [CAR_IMAGES.mercedesSedan1, CAR_IMAGES.mercedesSedan3],
    features: commonFeatures,
  },
  {
    id: '204762',
    year: 2018,
    make: 'Mercedes-Benz',
    model: 'E-Class',
    trim: 'E300 Luxury Sedan',
    price: 'Call for price!',
    downPayment: '$1000 Down',
    mileage: 37890,
    engine: '2.0L L4 DOHC 16V TURBO',
    transmission: 'SPEED AUTOMATIC',
    drivetrain: 'AWD',
    vin: 'WDDZF4KB5JA111222',
    exteriorColor: 'SELENITE GREY',
    interiorColor: 'BLACK',
    fuelType: 'Gasoline',
    stockNumber: '204762',
    images: [CAR_IMAGES.mercedesSedan2, CAR_IMAGES.mercedesSedan4],
    features: commonFeatures,
  },
  {
    id: '204770',
    year: 2020,
    make: 'Mercedes-Benz',
    model: 'GLA-Class',
    trim: 'GLA250 4MATIC',
    price: 'Call for price!',
    downPayment: '$1000 Down',
    mileage: 24560,
    engine: '2.0L L4 DOHC 16V TURBO',
    transmission: 'SPEED AUTOMATIC',
    drivetrain: 'AWD',
    vin: 'WDCTG4EB6LJ556677',
    exteriorColor: 'POLAR WHITE',
    interiorColor: 'BLACK',
    fuelType: 'Gasoline',
    stockNumber: '204770',
    images: [CAR_IMAGES.rangeRover2, CAR_IMAGES.rangeRover1],
    features: commonFeatures,
  },
  {
    id: '204772',
    year: 2017,
    make: 'Mercedes-Benz',
    model: 'GLA-Class',
    trim: 'GLA250',
    price: 'Call for price!',
    downPayment: '$1000 Down',
    mileage: 51230,
    engine: '2.0L L4 DOHC 16V TURBO',
    transmission: 'SPEED AUTOMATIC',
    drivetrain: 'FWD',
    vin: 'WDCTG4EB6HJ998877',
    exteriorColor: 'NIGHT BLACK',
    interiorColor: 'BLACK',
    fuelType: 'Gasoline',
    stockNumber: '204772',
    images: [CAR_IMAGES.rangeRover3, CAR_IMAGES.rangeRover4],
    features: commonFeatures,
  },
  {
    id: '204774',
    year: 2018,
    make: 'Mercedes-Benz',
    model: 'GLA-Class',
    trim: 'GLA250',
    price: 'Call for price!',
    downPayment: '$1000 Down',
    mileage: 44100,
    engine: '2.0L L4 DOHC 16V TURBO',
    transmission: 'SPEED AUTOMATIC',
    drivetrain: 'FWD',
    vin: 'WDCTG4EB2JJ334455',
    exteriorColor: 'COSMOS BLACK',
    interiorColor: 'ASH',
    fuelType: 'Gasoline',
    stockNumber: '204774',
    images: [CAR_IMAGES.rangeRover4, CAR_IMAGES.rangeRover2],
    features: commonFeatures,
  },
  {
    id: '204776',
    year: 2020,
    make: 'Mercedes-Benz',
    model: 'GLC-Class',
    trim: 'GLC300 4MATIC',
    price: 'Call for price!',
    downPayment: '$1000 Down',
    mileage: 27890,
    engine: '2.0L L4 DOHC 16V TURBO',
    transmission: 'SPEED AUTOMATIC',
    drivetrain: 'AWD',
    vin: 'W1NKM4KB0LF778899',
    exteriorColor: 'MOJAVE SILVER',
    interiorColor: 'BLACK',
    fuelType: 'Gasoline',
    stockNumber: '204776',
    images: [CAR_IMAGES.rangeRover1, CAR_IMAGES.rangeRover3],
    features: commonFeatures,
  },
  {
    id: '204778',
    year: 2017,
    make: 'Mercedes-Benz',
    model: 'GLE-Class',
    trim: 'AMG GLE 43',
    price: 'Call for price!',
    downPayment: '$1000 Down',
    mileage: 48750,
    engine: '3.0L V6 DOHC 24V TURBO',
    transmission: 'SPEED AUTOMATIC',
    drivetrain: 'AWD',
    vin: '4JGDA6EB6HA112233',
    exteriorColor: 'DIAMOND WHITE',
    interiorColor: 'BLACK/RED',
    fuelType: 'Gasoline',
    stockNumber: '204778',
    images: [CAR_IMAGES.rangeRover2, CAR_IMAGES.rangeRover4],
    features: commonFeatures,
  },
  {
    id: '204780',
    year: 2018,
    make: 'Mercedes-Benz',
    model: 'GLC-Class',
    trim: 'GLC300 4MATIC',
    price: 'Call for price!',
    downPayment: '$1000 Down',
    mileage: 35670,
    engine: '2.0L L4 DOHC 16V TURBO',
    transmission: 'SPEED AUTOMATIC',
    drivetrain: 'AWD',
    vin: 'WDC0G4KB0JF445566',
    exteriorColor: 'LUNAR BLUE',
    interiorColor: 'BLACK',
    fuelType: 'Gasoline',
    stockNumber: '204780',
    images: [CAR_IMAGES.mercedesSedan3, CAR_IMAGES.mercedesSedan1],
    features: commonFeatures,
  },
  {
    id: '204782',
    year: 2017,
    make: 'Mercedes-Benz',
    model: 'S-Class',
    trim: 'S550',
    price: 'Call for price!',
    downPayment: '$1000 Down',
    mileage: 32564,
    engine: '4.7L V8 DOHC 32V TURBO',
    transmission: 'SPEED AUTOMATIC',
    drivetrain: 'RWD',
    vin: 'WDDUG8CB6HA557788',
    exteriorColor: 'ANTHRACITE BLUE',
    interiorColor: 'PORCELAIN',
    fuelType: 'Gasoline',
    stockNumber: '204782',
    images: [CAR_IMAGES.mercedesSedan4, CAR_IMAGES.mercedesSedan2],
    features: commonFeatures,
  },
  {
    id: '204784',
    year: 2017,
    make: 'Mercedes-Benz',
    model: 'SL-Class',
    trim: 'SL550',
    price: 'Call for price!',
    downPayment: '$1000 Down',
    mileage: 22350,
    engine: '4.7L V8 DOHC 32V TURBO',
    transmission: 'SPEED AUTOMATIC',
    drivetrain: 'RWD',
    vin: 'WDDJK7DA5HF119966',
    exteriorColor: 'DESIGNO CARDINAL RED',
    interiorColor: 'BLACK',
    fuelType: 'Gasoline',
    stockNumber: '204784',
    images: [CAR_IMAGES.mercedesSedan1, CAR_IMAGES.mercedesSedan4],
    features: commonFeatures,
  },
];

export const OPENING_HOURS = [
  { day: 'Monday', time: '10:00 - 5:00' },
  { day: 'Tuesday', time: '10:00 - 5:00' },
  { day: 'Wednesday', time: '10:00 - 5:00' },
  { day: 'Thursday', time: '10:00 - 5:00' },
  { day: 'Friday', time: '10:00 - 5:00' },
  { day: 'Saturday', time: '10:00 - 5:00' },
  { day: 'Sunday', time: 'closed' },
];

export const STORE_HOURS = [
  { day: 'Monday', time: '9:00 AM - 6:00 PM' },
  { day: 'Tuesday', time: '9:00 AM - 6:00 PM' },
  { day: 'Wednesday', time: '9:00 AM - 6:00 PM' },
  { day: 'Thursday', time: '9:00 AM - 6:00 PM' },
  { day: 'Friday', time: '9:00 AM - 5:00 PM' },
  { day: 'Saturday', time: '9:00 AM - 5:00 PM' },
  { day: 'Sunday', time: '10:00 AM - 4:00 PM' },
];

export const COMPANY_INFO = {
  name: 'Tri State Auto Brokers, Inc.',
  address: '9905 Davidson Parkway',
  cityState: 'Stockbridge, GA 30281',
  phone: '470-878-6211',
  textUs: '470-878-6211',
  email: 'tristateautobrokers@outlook.com',
  since: 2010,
};
